# -*- coding: utf-8 -*-
"""Covid - Economie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwoV8MLKZ-IC4UmZKBKxabxA2c5BQkAk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data = pd.read_csv('/content/drive/MyDrive/unemployment analysis.csv')

data

# Remove countryode column
data.drop(columns = ['Country Code'], inplace = True)
# Set countryname column as Index
data.set_index('Country Name', inplace = True)

# Transpose dataset
data_T = data.T

fig = px.line(data_T[['United Kingdom', 'France', 'India']])
fig.show()